volumes:
  pgdata:

services:
  postgres:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

